version: "3.8"

services:
  # vault-api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile    
  #   env_file:
  #     - env/docker.env
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - mongodb
  #     - minio

  mongodb:
    image: mongo:latest
    env_file:
      - env/docker.env
    volumes:
      - ./data/mongo_data:/data/db
    ports: 
      - 27017:27017

  minio:
    image: minio/minio:latest      
    env_file:
      - env/docker.env
    volumes:
      - ./data/redis_minio:/data
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001