[features]
seeds = false
skip-lint = false
[programs.devnet]
vault = "GWDtSYERr74SqwyirLDfUBS15Hnp6gwsp49qtTQkwJhs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/d4fttasiii/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
